name: Contact Service
on: push
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
      CR_USERNAME: {{ env.GITHUB_ACTOR }}
      CR_PASSWORD: {{ env.GITHUB_TOKEN }}
      CR_HOST: ghcr.io
    defaults:
      run:
            working-directory: ./contact-service
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Test
        run: ./gradlew test
      - name: Push image
        run: ./gradlew publishImage
